//
//  CustomDefined.h
//  VPM
//
//  Created by LaiZhaowu on 13-12-6.
//
//

// Setting
#define DEVICE_TOKEN @"DEVICE_TOKEN"
#define IS_AUTO_DOWNLOAD_ON_WWAN @"IS_AUTO_DOWNLOAD_ON_WWAN"
#define IS_DISPLAY_IMAGE_ON_WWAN @"IS_DISPLAY_IMAGE_ON_WWAN"
#define ENABLED_ROMOTE_NOTIFICATION @"ENABLED_ROMOTE_NOTIFICATION"
#define DEFAULT_DISCOUNT_CATEGORY_ID @"DEFAULT_DISCOUNT_CATEGORY_ID"

// Notification
#define LOGIN_STATUS_CHANGE_NOTIFICATION @"LOGIN_STATUS_CHANGE_NOTIFICATION"

// Member
#define MEMBER_ID @"MEMBER_ID"
#define LOGIN_USER_NAME @"LOGIN_USER_NAME"
#define LOGIN_PASSWORD @"LOGIN_PASSWORD"
